name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install

      - name: Install dependencies for backend
        run: |
          cd backend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: private
          mask-password: true  # Mask the password in logs

      - name: Build Docker images
        run: |
          # Build frontend image
          cd frontend
          docker build -t capstone_proj_frontend .

          # Build backend image
          cd ../backend
          docker build -t capstone_proj_backend .

      - name: Tag and push frontend image
        run: |
          docker tag capstone_proj_frontend:latest 975050161532.dkr.ecr.us-east-1.amazonaws.com/capstone_proj_frontend:latest
          docker push 975050161532.dkr.ecr.us-east-1.amazonaws.com/capstone_proj_frontend:latest

      - name: Tag and push backend image
        run: |
          docker tag capstone_proj_backend:latest 975050161532.dkr.ecr.us-east-1.amazonaws.com/capstone_proj_backend:latest
          docker push 975050161532.dkr.ecr.us-east-1.amazonaws.com/capstone_proj_backend:latest

      - name: Deploy to ECS
        run: |
          # Define your ECS cluster name and service name
          ECS_CLUSTER_NAME="capstone-cluster"
          FRONTEND_SERVICE_NAME="capstone_proj_frontend"
          BACKEND_SERVICE_NAME="capstone-backend-service"

          # Update frontend service
          aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $FRONTEND_SERVICE_NAME --force-new-deployment

          # Update backend service
          aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $BACKEND_SERVICE_NAME --force-new-deployment
